import type {
  FlexCalculatorDensityOption,
  FlexCalculatorMarketDataRow,
  FlexCalculatorSettings,
  SelectOption,
} from '@/lib/flex-calculator/types'

export const DEFAULT_LOCATION_OPTIONS: SelectOption[] = [
  { value: 'cbd', label: 'Centrum' },
  { value: 'non_cbd', label: 'Poza centrum' },
]

export const DEFAULT_FITOUT_OPTIONS: SelectOption[] = [
  { value: 'basic', label: 'Podstawowy' },
  { value: 'enhanced', label: 'Wyższy' },
  { value: 'premium', label: 'Premium' },
]

export const DEFAULT_FLEX_LEASE_OPTIONS: SelectOption[] = [
  { value: '12', label: '12 miesięcy' },
  { value: '24', label: '24 miesiące' },
  { value: '36', label: '36 miesięcy' },
]

export const DEFAULT_CONVENTIONAL_LEASE_OPTIONS: SelectOption[] = [
  { value: '60', label: '60 miesięcy' },
  { value: '72', label: '72 miesiące' },
  { value: '84', label: '84 miesiące' },
  { value: '96', label: '96 miesięcy' },
  { value: '108', label: '108 miesięcy' },
  { value: '120', label: '120 miesięcy' },
]

export const DEFAULT_DENSITY_OPTIONS: FlexCalculatorDensityOption[] = [
  {
    key: 'dense',
    label: 'Gęsto',
    sort_order: 1,
    flex_office_sqm_per_desk: 3.5,
    conventional_sqm_per_person_min: 8,
    conventional_sqm_per_person_max: 10,
    conventional_sqm_per_person_avg: 9,
    is_active: true,
  },
  {
    key: 'standard',
    label: 'Standard',
    sort_order: 2,
    flex_office_sqm_per_desk: 4,
    conventional_sqm_per_person_min: 10,
    conventional_sqm_per_person_max: 12,
    conventional_sqm_per_person_avg: 11,
    is_active: true,
  },
  {
    key: 'spacious',
    label: 'Swobodnie',
    sort_order: 3,
    flex_office_sqm_per_desk: 4.5,
    conventional_sqm_per_person_min: 12,
    conventional_sqm_per_person_max: 15,
    conventional_sqm_per_person_avg: 13.5,
    is_active: true,
  },
]

export const DEFAULT_MARKET_DATA: FlexCalculatorMarketDataRow[] = [
  {
    city_slug: 'warszawa',
    city_label: 'Warszawa',
    sort_order: 1,
    is_active: true,
    headline_rent_cbd_eur: 26,
    non_cbd_deduction_eur: -10,
    service_charge_cbd_pln: 33.4,
    service_charge_non_cbd_pln: 33.4,
    flex_price_cbd_pln: 2500,
    flex_price_non_cbd_pln: 1500,
    fitout_contribution_cbd_eur: 600,
    fitout_contribution_non_cbd_eur: 400,
    fitout_cost_basic_eur: 1300,
    fitout_cost_enhanced_eur: 1500,
    fitout_cost_premium_eur: 1600,
  },
  {
    city_slug: 'krakow',
    city_label: 'Kraków',
    sort_order: 2,
    is_active: true,
    headline_rent_cbd_eur: 20,
    non_cbd_deduction_eur: -5,
    service_charge_cbd_pln: 27.3,
    service_charge_non_cbd_pln: 27.3,
    flex_price_cbd_pln: 1700,
    flex_price_non_cbd_pln: 1200,
    fitout_contribution_cbd_eur: 400,
    fitout_contribution_non_cbd_eur: 300,
    fitout_cost_basic_eur: 500,
    fitout_cost_enhanced_eur: 1050,
    fitout_cost_premium_eur: 1950,
  },
  {
    city_slug: 'poznan',
    city_label: 'Poznań',
    sort_order: 3,
    is_active: true,
    headline_rent_cbd_eur: 16,
    non_cbd_deduction_eur: -6,
    service_charge_cbd_pln: 27.3,
    service_charge_non_cbd_pln: 27.3,
    flex_price_cbd_pln: 1300,
    flex_price_non_cbd_pln: 1100,
    fitout_contribution_cbd_eur: 350,
    fitout_contribution_non_cbd_eur: 200,
    fitout_cost_basic_eur: 550,
    fitout_cost_enhanced_eur: 900,
    fitout_cost_premium_eur: 1450,
  },
  {
    city_slug: 'wroclaw',
    city_label: 'Wrocław',
    sort_order: 4,
    is_active: true,
    headline_rent_cbd_eur: 15,
    non_cbd_deduction_eur: -4,
    service_charge_cbd_pln: 27.3,
    service_charge_non_cbd_pln: 27.3,
    flex_price_cbd_pln: 1500,
    flex_price_non_cbd_pln: 1150,
    fitout_contribution_cbd_eur: 300,
    fitout_contribution_non_cbd_eur: 200,
    fitout_cost_basic_eur: 550,
    fitout_cost_enhanced_eur: 900,
    fitout_cost_premium_eur: 1450,
  },
  {
    city_slug: 'katowice',
    city_label: 'Katowice',
    sort_order: 5,
    is_active: true,
    headline_rent_cbd_eur: 14,
    non_cbd_deduction_eur: -5,
    service_charge_cbd_pln: 27.3,
    service_charge_non_cbd_pln: 27.3,
    flex_price_cbd_pln: 1300,
    flex_price_non_cbd_pln: 1100,
    fitout_contribution_cbd_eur: 300,
    fitout_contribution_non_cbd_eur: 200,
    fitout_cost_basic_eur: 550,
    fitout_cost_enhanced_eur: 900,
    fitout_cost_premium_eur: 1450,
  },
  {
    city_slug: 'lodz',
    city_label: 'Łódź',
    sort_order: 6,
    is_active: true,
    headline_rent_cbd_eur: 12,
    non_cbd_deduction_eur: -6,
    service_charge_cbd_pln: 27.3,
    service_charge_non_cbd_pln: 27.3,
    flex_price_cbd_pln: 1100,
    flex_price_non_cbd_pln: 1100,
    fitout_contribution_cbd_eur: 300,
    fitout_contribution_non_cbd_eur: 200,
    fitout_cost_basic_eur: 550,
    fitout_cost_enhanced_eur: 900,
    fitout_cost_premium_eur: 1450,
  },
  {
    city_slug: 'trojmiasto',
    city_label: 'Trójmiasto',
    sort_order: 7,
    is_active: true,
    headline_rent_cbd_eur: 15,
    non_cbd_deduction_eur: -6,
    service_charge_cbd_pln: 27.3,
    service_charge_non_cbd_pln: 27.3,
    flex_price_cbd_pln: 1500,
    flex_price_non_cbd_pln: 1200,
    fitout_contribution_cbd_eur: 400,
    fitout_contribution_non_cbd_eur: 300,
    fitout_cost_basic_eur: 760,
    fitout_cost_enhanced_eur: 900,
    fitout_cost_premium_eur: 1450,
  },
]

export const DEFAULT_FLEX_CALCULATOR_SETTINGS: FlexCalculatorSettings = {
  id: 'default',
  intro_eyebrow: 'Kalkulator flex',
  intro_title: 'Porównaj flex z najmem konwencjonalnym na porównywalnych założeniach',
  intro_body:
    'To narzędzie pomaga szybko oszacować różnice kosztowe między biurem serwisowanym a najmem konwencjonalnym dla Twojego zespołu. Największą wagę mają tu dwa wskaźniki: łączne zobowiązanie oraz koszt konwencji liczony za identyczny okres jak planowana umowa flex.',
  intro_disclaimer_approx:
    'Wartości w kalkulatorze mają charakter orientacyjny i służą do wstępnego oszacowania scenariuszy.',
  intro_disclaimer_market:
    'Założenia opierają się na aktualnych danych rynkowych opracowywanych przez zespół Colliers, ale z natury rzeczy pozostają uśrednione.',
  intro_disclaimer_support:
    'Jeśli będziesz szukać biura z udziałem Colliers, pomożemy przełożyć te estymacje na realne oferty, negocjacje i rekomendację najlepszego modelu.',
  default_headcount: 150,
  default_city_slug: 'warszawa',
  default_location_type: 'cbd',
  default_fitout_standard: 'enhanced',
  default_density_key: 'spacious',
  default_flex_lease_months: 12,
  default_conventional_lease_months: 60,
  utilities_and_maintenance_eur_per_sqm: 5,
  flex_common_area_sqm_per_desk: 0.9,
  add_on_factor: 1.06,
  rent_free_months_per_year: 1,
  location_options: DEFAULT_LOCATION_OPTIONS,
  fitout_options: DEFAULT_FITOUT_OPTIONS,
  flex_lease_options: DEFAULT_FLEX_LEASE_OPTIONS,
  conventional_lease_options: DEFAULT_CONVENTIONAL_LEASE_OPTIONS,
}
